name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4
      - name: Run tests
        run: make test
